# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aflete' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Aflete

  platform :ios, '9.0'
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTNetwork',
    'RCTWebSocket'
  ]

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  # pod 'react-native-video', :path => '../node_modules/react-native-video'

  # pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  # pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'Picker', :path => '../node_modules/react-native-picker'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'AfleteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
