export const LOADING = 'LOADING'
export const LOADING_STATUS = 'LOADING_STATUS'
export const FINISH_LOADING = 'FINISH_LOADING'
export const APP_CONNECTIVITY_CHANGE = 'APP_CONNECTIVITY_CHANGE'

export const STORE_PRODUCTS = 'STORE_PRODUCTS'
export const STORE_SINGLE_PRODUCT = 'STORE_SINGLE_PRODUCT'
export const STORE_TEMP_EXERCISE_WEIGHTS = 'STORE_TEMP_EXERCISE_WEIGHTS'
export const STORE_EXERCISE_WEIGHTS = 'STORE_EXERCISE_WEIGHTS'
export const STORE_PRODUCT_NOTE = 'STORE_PRODUCT_NOTE'
export const STORE_EXERCISE_NOTE = 'STORE_EXERCISE_NOTE'
export const EXERCISE_NOTES_SAVED_TO_DB = 'EXERCISE_NOTES_SAVED_TO_DB'
export const EXERCISE_WEIGHTS_SAVED_TO_DB = 'EXERCISE_WEIGHTS_SAVED_TO_DB'
export const WORKOUT_SESSION_COMPLETED = 'WORKOUT_SESSION_COMPLETED'
export const WORKOUT_SESSION_RESTARTED = 'WORKOUT_SESSION_RESTARTED'



// // Workouts

// export const MODIFY_EXERCISE_WEIGHTS = 'MODIFY_EXERCISE_WEIGHTS'
// export const ADD_EXERCISE_WEIGHTS = 'ADD_EXERCISE_WEIGHTS'
// export const ADD_EXERCISE_NOTE = 'ADD_EXERCISE_NOTE'